import './globals.scss'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Provider from './lib/Provider'
import { getSettings } from './lib/settings'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Fatigue Diary',
  description: 'Generated by create next app',
}


export default async function RootLayout({ children }) {
  let settings = await getSettings();

  return (
    <html lang="en" className={settings.theme !== 1 && "dark"}>
      <body className={inter.className}>
        <Provider>
          <Navbar />
          <main className="h-[calc(100vh-64px-24px-1px)]"> {/* -nav-margintop-navborder */}
            {children}
          </main>
        </Provider>
      </body>
    </html>
  )
}
